### PR TITLE
Credits Persist-seq original pipeline for the Pseudo-bulk scRNA-seq pipeline

### PR DESCRIPTION
**Pull request by pcm32**
Adds credits on the Pseudo-bulk scRNA-seq pipeline, and mentions main differences for user's awareness.

### CODE REVIEW

**Comment by pavanvidem** [comment]
@pcm32 thanks! The workflows on Galaxy can still be changed after sharing/publication. I am not sure whether there is a way to freeze and version a workflow on Galaxy. If we are citing a specific version of the original workflow here, then it would be good to have this version frozen somewhere (like WorkflowHub or IWC). That's just an idea. Maybe there are better ways to do it.

**Comment by pcm32** [comment]
Maybe we can add the file on a supplementary directory here if you prefer? I don't mind. I don't tend to unshare things off the main galaxy instances, but I understand why you suggest it.

**Comment by pcm32** [comment]
Adding to IWC is probably too much work for what I'm after.

**Comment by pavanvidem** [comment]
@mvdbeek is it allowed to have such a supplementary directory with an additional workflow? Is there a better solution to cite a specific version of a published Galaxy workflow? something similar to history achieving but for workflows?

**Comment by mvdbeek** [comment]
I don't understand, all IWC workflows are versioned. I don't see a problem with the readme either.

**Review by mvdbeek — APPROVED** [review]

**Comment by pavanvidem** [comment]
@mvdbeek, if you think we can keep that workflow link, please go ahead and merge.

**Comment by mvdbeek** [comment]
It's a link, just like GTN or wikipedia links they can go away, I don't think this is a problem.

**Comment by mvdbeek** [comment]
Attention: deployment failure!

https://github.com/galaxyproject/iwc/actions/runs/11932563263

**Pull request merged**
