### PR TITLE
Clarify masthead links

### PR DESCRIPTION
**Pull request by martenson**
I assume it was meant like this

### CODE REVIEW

**Comment by lldelisle** [comment]
For me these buttons were unclear... Can we use more meaningful labels?

**Comment by lldelisle** [comment]
Can we add a 'Contribute' which would link to https://github.com/galaxyproject/iwc/blob/main/workflows/README.md#adding-workflows?

**Comment by mvdbeek** [comment]
Yeah, I would do "Contribute" -> https://github.com/galaxyproject/iwc/blob/main/workflows/README.md#adding-workflows and "GitHub" -> https://github.com/galaxyproject/iwc

**Comment by martenson** [comment]
Good points

**Review by mvdbeek — APPROVED** [review]
LGTM, thank you @martenson!

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/11742395094

**Pull request merged**
