### PR TITLE
[WIP] VGP workflows: hifiasm

### PR DESCRIPTION
**Pull request by gallardoalba**

### CODE REVIEW

**Comment by gallardoalba** [comment]
Part of https://github.com/galaxyproject/iwc/pull/56

**Comment by abueg** [comment]
READMEs for hifiasm, hifiasm-trio, and hifiasm-hic added!

**Comment by bgruening** [comment]
Thanks @abueg

**Comment by gallardoalba** [comment]
> READMEs for hifiasm, hifiasm-trio, and hifiasm-hic added!

Thanks!

**Comment by gallardoalba** [comment]
Could you approve the test run @mvdbeek?

**Comment by gallardoalba** [comment]
This is the error, but not sure how to fix it @Delphine-L @mvdbeek 

https://gist.github.com/gallardoalba/dbacece3673a3946e9fb489f88bef84e#file-hifiasm_error_report-txt

**Comment by gallardoalba** [comment]
Replaced by https://github.com/galaxyproject/iwc/pull/56

**Pull request closed without merging**
