### PR TITLE
Updating workflows/data-fetching/sra-manifest-to-concatenated-fastqs from 0.3 to 0.4

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following workflow: **workflows/data-fetching/sra-manifest-to-concatenated-fastqs**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

By comparing with the latest versions available on the ToolShed, it seems the following tools are outdated:
* `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_find_and_replace/9.3+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_find_and_replace/9.3+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.10+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.1.0+galaxy0`

The workflow release number has been updated from 0.3 to 0.4.

### CODE REVIEW

**Comment by lldelisle** [comment]
I don't understand why this workflow get a `fasterq-dump command not found` while the other workflow with the same version of fasterq-dump has no issue...

**Comment by mvdbeek** [comment]
It appears that there is no container for the new fasterq-dump tool, and the mulled build attempt fails:
```
galaxy.tool_util.deps.containers ERROR 2024-04-09 08:27:27,121 [pN:main.1,p:5403,tN:LocalRunner.work_thread-0] Could not get container description for tool 'toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.1.0+galaxy0'
Traceback (most recent call last):
  File "/tmp/tmpcknz3km0/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 363, in find_best_container_description
    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpcknz3km0/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 394, in resolve
    container_description = container_resolver.resolve(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpcknz3km0/galaxy-dev/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 761, in resolve
    mull_targets(targets, involucro_context=self.involucro_context, **self._mulled_kwds)
  File "/tmp/tmpcknz3km0/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 352, in mull_targets
    ret = involucro_context.exec_command(involucro_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpcknz3km0/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 422, in exec_command
    shutil.rmtree("./build")
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/shutil.py", line 703, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/shutil.py", line 701, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'ptardiff'
```

**Comment by lldelisle** [comment]
And here it seems that it worked: https://github.com/galaxyproject/iwc/actions/runs/8603413924/job/23575573762#step:6:3047

I guess the easiest is to wait for the publication of the container right?

**Comment by mvdbeek** [comment]
I've triggered the build: https://github.com/galaxyproject/planemo-monitor/actions/runs/8494335497

**Comment by lldelisle** [comment]
I forgot that you need to rerun all jobs if not the failed test output is still there...

**Review by lldelisle — APPROVED** [review]

**Pull request merged**
