### PR TITLE
Updating workflows/transcriptomics/rnaseq-pe from 0.1 to 0.2

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

By comparing with the latest versions available on the ToolShed, it seems the following tools are outdated:
* `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a`

The workflow release number has been updated from 0.1 to 0.2.

### CODE REVIEW

**Comment by lldelisle** [comment]
What is strange is that in the file `.ga` it changed from galaxy0 to galaxy1...

**Comment by lldelisle** [comment]
The tool toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a+galaxy1 is not yet installed in usegalaxy.org.
I need to change the test case because it is too large and takes too long.

**Comment by mvdbeek** [comment]
It's also installed now and passing.

**Comment by lldelisle** [comment]
Yes I was wondering if I could change the input test data as I think the CI is a bit long...

**Comment by lldelisle** [comment]
But maybe I can do it in a second time.

**Review by mvdbeek — APPROVED** [review]
That's up to you, there's no cost to having another version :)

**Comment by lldelisle** [comment]
Reducing the size of input test did not change the running time...

**Pull request merged**
