### PR TITLE
IWC site refactoring, cleanup, styling

### PR DESCRIPTION
**Pull request by dannon**
Refactoring layouts, data fetching, and more.  Lots of extra polish, loading indicators, improvement of local preference storage.

Adjusts to galaxy brand colors, stick with a light mode only for now -- we can iterate on dark as we don't have good galaxy dark branding yet.

Lots more tweaks in commits.

image

image

### CODE REVIEW

**Comment by lldelisle** [comment]
I don't know if you are working on this part or not but it would be super cool to have something like what the GTN has:
https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html#admin-missing-tools

**Comment by dannon** [comment]
@lldelisle We'll definitely add that -- I'll probably add it in a subsequent update though.  I think this one's about ready as a nice incremental update.

**Comment by mvdbeek** [comment]
This looks so cool, thanks a lot @dannon!

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/11859934435

**Pull request merged**
