### PR TITLE
add bacterial genome assembly

### PR DESCRIPTION
**Pull request by pimarin**
This workflow com from the abromics project in genomic :
Bacterial assembly from illumina paired-end short read and some annotations

We followed the recommandaion to publish the workflow (licence, author list and email, steps annotations...)

- [X]  Workflow inported from [usegalaxy.fr](https://usegalaxy.fr) using `planemo workflow_test_init` to use a valid invocation
- [X]  Workflow tests passed using `planemo test` command on the usegalaxy.fr server
- [X] Readme.md written
- [X]  CHANGELOG.md written
- [X]  CHANGELOG.md written
- [X]  .dockstore.yml written

### CODE REVIEW

**Comment by pimarin** [comment]
I received this message :
`Failed to run workflow, at least one job is in [error] state.`
But no more informations... to debug

**Comment by pimarin** [comment]
@bebatut ?

**Comment by pimarin** [comment]
I'm wondering how the test could deal with tool linked to a database (here kraken, bracken and bakta)

**Comment by lldelisle** [comment]
Hi,
Welcome to IWC. This is great to have new contributors. I found the error:
<p dir="auto"><strong>Step 6: bracken_abundance_estimation</strong>:</p>
<ul dir="auto">
<li>
<p dir="auto">step_state: scheduled</p>
</li>
<li>
<details open=""><summary>Jobs</summary>
<ul dir="auto">
<li>
<p dir="auto"><strong>Job 1:</strong></p>
<ul dir="auto">
<li>Job state is error</li>
</ul>
<p dir="auto"><strong>Traceback:</strong></p>
<ul dir="auto">
<li>
<div class="highlight highlight-text-shell-session notranslate position-relative overflow-auto" dir="auto"><pre class="notranslate"><span class="pl-c1">Traceback (most recent call last):</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 293, in prepare_job</span>
<span class="pl-c1">    job_wrapper.prepare()</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1255, in prepare</span>
<span class="pl-c1">    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/evaluation.py", line 139, in set_compute_environment</span>
<span class="pl-c1">    self._validate_incoming(incoming)</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/evaluation.py", line 282, in _validate_incoming</span>
<span class="pl-c1">    visit_input_values(self.tool.inputs, incoming, validate_inputs)</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 224, in visit_input_values</span>
<span class="pl-c1">    callback_helper(</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/parameters/__init__.py", line 159, in callback_helper</span>
<span class="pl-c1">    new_value = callback(**args)</span>
<span class="pl-c1">                ^^^^^^^^^^^^^^^^</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/evaluation.py", line 279, in validate_inputs</span>
<span class="pl-c1">    value = input.from_json(value, request_context, context)</span>
<span class="pl-c1">            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</span>
<span class="pl-c1">  File "/tmp/tmpq0v4a6tr/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 1030, in from_json</span>
<span class="pl-c1">    raise ParameterValueError(</span>
<span class="pl-c1">galaxy.tools.parameters.basic.ParameterValueError: parameter 'kmer_distr': requires a value, but no legal values defined</span>
</pre><div class="zeroclipboard-container position-absolute right-0 top-0">
    
  </div></div>
</li>
</ul>
<p dir="auto"><strong>Job Parameters:</strong></p>
<ul dir="auto">
<li>

Job parameter | Parameter value
-- | --
__input_ext | "input"
__workflow_invocation_uuid__ | "40486ee1bad711eeb212e5dc4c4f5b44"
chromInfo | "/tmp/tmpq0v4a6tr/galaxy-dev/tool-data/shared/ucsc/chrom/?.len"
dbkey | "?"
kmer_distr | "bf6177af-7f5b-4005-9bec-fc7c89c3cb1c"
level | "S"
logfile_output | false
out_report | true
threshold | "10"

</li></ul></li></ul></details></li></ul>

If you see how to solve it, tell me, if not I will investigate more deeply your workflow.

**Comment by pimarin** [comment]
Thank you so much @lldelisle !! But I don't understand how you extracted this information ? I did'nt see anything to help me.

**Comment by lldelisle** [comment]
In the report that have been posted there are arrows you can click on:

[Screencast from 01-25-2024 10:12:58 AM.webm](https://github.com/galaxyproject/iwc/assets/30404086/c666b569-4653-4a1d-98a5-d6f75a1b1be6)

**Comment by lldelisle** [comment]
Now we are at the issue with the database:
`galaxy.tools.parameters.basic.ParameterValueError: parameter 'kraken2_database': an invalid option ('2023-08-24T153645Z_standard_prebuilt_pluspf_16gb_2022-06-07') was selected (valid options: 2022-07-06T094102Z_standard_prebuilt_standard_2022-06-07,2020-11-24T164216Z_silva_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,2022-02-02T162959Z_silva_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,k2_standard_20210517,k2_minusb_20210517,2020-11-24T170532Z_rdp_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,2022-09-05T092205Z_standard_prebuilt_pluspfp_2022-06-07,2020-11-24T172646Z_greengenes_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,fungi2019-03,plasmid2019-03,viral2019-03,16S_SILVA138_k2db2021-08,2022-02-02T162953Z_greengenes_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,kalamari,2020-11-26T021706Z_standard_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7,2022-09-04T165121Z_standard_prebuilt_pluspf_2022-06-07,2022-08-04T105935Z_standard_prebuilt_viral_2022-06-07,k2_pluspf_20210517)`

**Comment by bgruening** [comment]
Is that only kraken2 or is anything else missing?

**Comment by pimarin** [comment]
> Is that only kraken2 or is anything else missing?

The name of the databases provided on my galaxy server are differents from the github CI/CD tests, so I need to receive the error to update the good name...

**Comment by pimarin** [comment]
Moreover the kraken2 tool failed because the database is so big and it can"t allocate  enough memory.

```
"stderr": "Loading database information...Failed attempt to allocate 65426688000bytes;\nyou may not have enough free memory to load this database.\nIf your computer has enough RAM, perhaps reducing memory usage from\nother programs could help you load this database?\nclassify: unable to allocate hash table memory",
```

**Comment by pimarin** [comment]
theI think the probleme will be the same with bracken and maybe bakta tools

**Comment by pimarin** [comment]
Even if i update the database name to pass the test I still locked with the same error as you mentionend @lldelisle https://github.com/galaxyproject/iwc/pull/323#issuecomment-1909681346.
So kraken seem to be ok now but when I give a database name for bracken I d'ont have the same error as kraken : error because not use the good name of the database provided. The message maybe indicate that not database are available to bracken maybe ? because the parameter `kmer_dist`is provided by the name of the database

**Comment by pimarin** [comment]
Maybe this workflow need to be placed in another place instead of `genome-assembly` for example antimicrobial-identification

**Comment by pimarin** [comment]
The parameter `kmer_distrib` still a problem, so after checking a name to the bracken DB, I show on usegalaxy.eu that kraken2 and bracken have not the same database list (count) and name. So I try to use a shared name for both tools.

**Comment by bebatut** [comment]
@pimarin we need to use the DBs on CVMFS. There is an open PR to add Kraken and Bracken there: https://github.com/galaxyproject/idc/pull/33/files

**Comment by mvdbeek** [comment]
Is this the same workflow as the one merged in https://github.com/galaxyproject/iwc/pull/438 ?

**Comment by clsiguret** [comment]
> Is this the same workflow as the one merged in #438 ?

Not just this one :smile: I split this workflow to #437 #438 #439 #441 . 
We can close this PR! :tada:
Thanks :smile:

**Pull request closed without merging**
