### PR TITLE
ChIP SR

### PR DESCRIPTION
**Pull request by lldelisle**
New workflow ChIP for Single Read. It is the corresponding ChIP PE but for single read.

### CODE REVIEW

**Comment by lldelisle** [comment]
Ideally, I would have liked to propose the user to choose between 'model' and 'nomodel' for macs2 but it seems that it cannot be a workflow parameter as it is a conditional.

**Comment by mvdbeek** [comment]
Hmm, this might be another case where we need conditionals.

**Comment by lldelisle** [comment]
You mean where we need conditional steps, right?

**Comment by mvdbeek** [comment]
Yes!

**Comment by lldelisle** [comment]
Meanwhile we could do subworkflows but I don't know if it worths.

**Comment by mvdbeek** [comment]
So far probably not, but I think we could ultimately share the multiqc/big/macs2 summary steps with the PE workflow via gxformat2 references. Can you also change the name to lowercase (chip-seq-sr or chipseq-sr)?

**Comment by lldelisle** [comment]
Even if ChIPseq_PE is in upper case?
Or should I modify both?

**Comment by mvdbeek** [comment]
Yeah, I thought about that too late, but if you can change both that would be great. I can rename the PE one in github/dockstore/workflowhub

**Comment by lldelisle** [comment]
Should I write something in the changelog of PE?
Can we do something as 'mark as deprecated' in both repositories?

**Comment by lldelisle** [comment]
:tada:

**Pull request merged**
