### PR TITLE
Updating workflows/data-fetching/parallel-accession-download from 0.1.6 to 0.1.7

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following workflow: **workflows/data-fetching/parallel-accession-download**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

By comparing with the latest versions available on the ToolShed, it seems the following tools are outdated:
* `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.5+galaxy3` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.8+galaxy0`

The workflow release number has been updated from 0.1.6 to 0.1.7.

### CODE REVIEW

**Comment by lldelisle** [comment]
I've just restarted the CI because I don't see why it should fail.

**Comment by mvdbeek** [comment]
That's a bug in planemo where we shut down too early, i introduced this with making planemo more resilient to failing tests ... 😆

**Comment by lldelisle** [comment]
This is waiting for a planemo release.

**Comment by lldelisle** [comment]
It works. Should I merge it?

**Pull request merged**
