### PR TITLE
Comment on PR with result of workflow test

### PR DESCRIPTION
**Pull request by lldelisle**
This is highly inspired from [this post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
Contrarily to current code it works for PR from forks.

I deployed it on my fork and the issue I see is that when the PR workflow does not generate a combined test then the action Comment on the pull request fails because there is no artifact. See https://github.com/lldelisle/iwc/actions/runs/7492377134/job/20395726430

But I don't know how to introduce a if within the script to prevent filtering artifact if it is empty.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
> when the PR workflow does not generate a combined test then the action Comment on the pull request fails because there is no artifact

In which cases there is no combined test?

**Comment by lldelisle** [comment]
For example, this PR do not generate a combined test... All PRs that do not modify workflows...

**Comment by mvdbeek** [comment]
that sounds ok to me ? and we'd also not want to get a comment if the PR passed ... i am in fact worried about getting spammed, considering that I already get a notification for every failed run of my own PRs

**Review by mvdbeek — APPROVED** [review]

**Comment by lldelisle** [comment]
May I merge?

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/7503040653

**Comment by lldelisle** [comment]
:+1:

**Pull request merged**
