### PR TITLE
Fix AF and DP_ALT handling in reporting workflow

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Comment by wm75** [comment]
In the by-variants report both the list of all samples with a given variant and the corresponding list of AFs are dependent on the order of the input samples in the collection, which I had built differently in my own testing. Should be fixed now.

**Comment by wm75** [comment]
but there seems to be some general issue with running tests currently

**Comment by wm75** [comment]
Seems to have been a temporary issue that also impacted the weekly tests of all WFs.
Tests are passing now again :)

**Comment by mvdbeek** [comment]
Yeah, looks like the cvmfs apt repository was down.

**Comment by wm75** [comment]
Don't want to merge my own PR, but I think it's ready :)

**Pull request merged**
