### PR TITLE
Updating workflows/epigenetics/consensus-peaks from 1.1 to 1.2 

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following workflow: **workflows/epigenetics/consensus-peaks**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

By comparing with the latest versions available on the ToolShed, it seems the following tools are outdated:
* `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.15.1+galaxy2` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.20+galaxy3`
* `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.11+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.24.1+galaxy0`
* `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.15.1+galaxy2` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.20+galaxy3`
* `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.11+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.24.1+galaxy0`
* `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.15.1+galaxy2` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.20+galaxy3`
* `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.11+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.24.1+galaxy0`

The workflow release number has been updated from 1.1 to 1.2.

### CODE REVIEW

**Comment by lldelisle** [comment]
I am waiting for the autoupdate of the other workflows of the directory.

**Review by lldelisle — APPROVED** [review]

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/11022045695

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/11022045695

**Comment by lldelisle** [comment]
I have a `Could not get container description for tool 'toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.31.1+galaxy0'` (https://github.com/galaxyproject/iwc/actions/runs/11022045695/job/30611417989#step:6:7743) while bedtools has not been upgraded and in the CI of the PR I got https://github.com/galaxyproject/iwc/actions/runs/11021689499/job/30609359520#step:6:5783 `galaxy.tool_util.deps.containers INFO 2024-09-24 20:54:59,965 [pN:main.1,p:5299,tN:LocalRunner.work_thread-1] Checking with container resolver [MulledDockerContainerResolver[namespace=biocontainers]] found description [ContainerDescription[identifier=quay.io/biocontainers/bedtools:2.31.1--hf5e1c6e_2,type=docker]]`. Any idea?

**Comment by mvdbeek** [comment]
That's quay.io failing to respond to the request that lists container images. A rerun will likely work

**Comment by lldelisle** [comment]
OK, I run it twice but let's hope at the end it will work.
Thanks

**Comment by lldelisle** [comment]
The third time was the good one.

**Pull request merged**
