### PR TITLE
Create markdown summary, post back as comment if test failed

### PR DESCRIPTION
**Pull request by mvdbeek**
See https://github.com/mvdbeek/iwc/pull/5#issuecomment-1798717986 and https://github.com/mvdbeek/iwc/actions/runs/6785381095?pr=5 for an example

### CODE REVIEW

**Comment by bgruening** [comment]
:tada:

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/6787943615

**Comment by lldelisle** [comment]
Waouh. I missed that but this is super cool!

**Comment by mvdbeek** [comment]
It doesn't work though, for some reason we're not getting the proper PR number, even though it works fine on my fork ...

**Comment by lldelisle** [comment]
mmmh :woman_shrugging:

**Comment by lldelisle** [comment]
I tested it on my fork. And I got a PR number. But in both cases (your and mine, the PR comes from a branch of the same fork). I will try to make a PR from your fork or the contrary.

**Comment by lldelisle** [comment]
https://github.com/lldelisle/iwc/pull/6

**Comment by lldelisle** [comment]
It seems that the github action do not find the PR number if it is a PR coming from another fork.

**Comment by lldelisle** [comment]
https://github.com/8BitJonny/gh-get-current-pr/issues/293

**Pull request merged**
