### PR TITLE
[BHEU2024] Update workflows/imaging/fluorescence-nuclei-segmentation-and-counting from 0.1 to 0.2

### PR DESCRIPTION
**Pull request by kostrykin**
Workflow: https://github.com/galaxyproject/iwc/tree/main/workflows/imaging/fluorescence-nuclei-segmentation-and-counting

The automatic update failed: https://github.com/galaxyproject/iwc/pull/361

This PR upgrades the tool versions and migrates the tests to use `image_diff` comparison method for verification, which is more robust.

Fix https://github.com/beatrizserrano/BH2024-project17/issues/5

### CODE REVIEW

**Review by lldelisle — APPROVED** [review]
Looks good to me

**Comment by bgruening** [comment]
So cool, thanks @kostrykin

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/iwc/actions/runs/11801119308

**Comment by lldelisle** [comment]
I relaunched the CI.

**Pull request merged**
