### PR TITLE
qiime2: remove spaces from names in dockstore.yml

### PR DESCRIPTION
**Pull request by bernt-matthias**
and shorten

### CODE REVIEW

**Comment by lldelisle** [comment]
Can you add the CHANGELOG.md, please?
@mvdbeek  Do this need a bump version? I would say yes.

**Comment by bernt-matthias** [comment]
For bumping the version I just punp it in `.workflowhub.yml`?

**Comment by mvdbeek** [comment]
Yeah, since we did create a deployment and released a version.

**Review by lldelisle — APPROVED** [review]

**Comment by lldelisle** [comment]
I love this automation with workflow report...

**Comment by bernt-matthias** [comment]
> I love this automation with workflow report...

Only problem is that this is not the report for the latest version .. I think .. https://github.com/galaxyproject/iwc/issues/420

But the test might still be wrong. Lets see :)

**Comment by lldelisle** [comment]
No, it was the report of the first commit. It does not show the report if the tests pass.

**Comment by lldelisle** [comment]
Should I merge?

**Review by mvdbeek — APPROVED** [review]

**Comment by bernt-matthias** [comment]
> Should I merge?

Yes, please.

**Pull request merged**
